spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-54-235-98-1.compute-1.amazonaws.com:5432/d1kn6doudusmg5
    driver-class-name: org.postgresql.Driver
    username: tnxtmwpweymeyd
    password: b9940c6927e8defedd9f8eb11b3a6a934c88b7bd56ed89ddcb38f34d5e829458
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5

logging:
  level:
    root: INFO
    org.springframework: INFO