spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: update
    properties:
      hibernate:
        order_insert: true
        dialect: org.hibernate.dialect.PostgerSQLDialect
        jdbc:
          bacth_size: 50
          lob:
            non_contextual_creaton: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/tour_of_heroes
    username: foo
    password: bar
    driverClassName: org.postgresql.Driver
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5

